name: 1. Build

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

  pull_request:

  workflow_dispatch:

#  schedule:
#    - cron:  '0 5,17 * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Build with Maven Wrapper
        run: ./mvnw -B package -DskipTests

      - name: Run tests
        run: ./mvnw -B test
