name: 2. Build with cache

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  workflow_dispatch:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'
          cache: 'maven'

      - name: Build with Maven Wrapper
        run: ./mvnw -B package -DskipTests

      - name: Run tests
        run: ./mvnw -B test
