name: 5. Get secret and variable

on:
  workflow_dispatch:

jobs:
  info:
    runs-on: ubuntu-latest
    steps:

      - name: Echo variable
        run: echo ${{ vars.VARIABLENAME }}

      - name: Echo secret
        run: echo ${{ secrets.SECRETNAME }}

      - name: Echo secret word count
        run: echo -n ${{ secrets.SECRETNAME }} | wc -c

      - name: Echo secret word count
        run: echo -n ${{ secrets.SECRETNAME }} | sed 's/./& /g'
