name: 6. Deploy app to Azure

on:
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'lunch-learn-bhs'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'
          cache: 'maven'

      - name: Build with Maven Wrapper
        run: ./mvnw package

      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '${{ github.workspace }}/target/*.jar'
