name: 7. Containerize application with input

on:
  workflow_dispatch:
    inputs:
      container_tag:
        description: 'Container tag'
        required: true
        default: 'latest'
        type: string

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Echo container image
        run: echo "building image with tag name ${{ inputs.container_tag }}"

      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'
          cache: 'maven'

      - name: Build with Maven Wrapper
        run: ./mvnw --batch-mode spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName="ghcr.io/timonb/lunch-learn-demo:${{ inputs.container_tag }}"

      - name: Login to GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: docker push ghcr.io/timonb/lunch-learn-demo:${{ inputs.container_tag }}
